

services:
  postgres:
    image: postgres:16-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    # healthcheck:          
    #   test: ["CMD-SHELL", "pg_isready -U keycloak"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres           
    networks:
      - internal
      - public

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    ports:
      - "8200:8200"
    networks:
      - public

  # Backend test (tạm thời)
  backend:
    build: ./backend  
    container_name: backend-api
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_JWKS_URI: ${KEYCLOAK_JWKS_URI}
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      VAULT_ENABLED: "true"
      DEMO_JWT_ISSUER: http://localhost:3000/demo-idp
      DEMO_JWT_AUDIENCE: secure-api
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 120
      MAX_BODY_BYTES: 1048576
      AUDIT_LOG_STDOUT: "true"
    depends_on:
      - vault
    networks:
      - public

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data:
